version: '{build}'

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x86
      FLAGS: ""
      GENERATOR: Visual Studio 15 2017

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x64
      FLAGS: ""
      GENERATOR: Visual Studio 15 2017
      
init:
  - cmake --version
  - msbuild /version
  
before_build:
  - git submodule update --init --recursive
  - cmake . -G "%GENERATOR%" -DBOOST_ROOT=C:\Libraries\boost_1_67_0

build_script:
  - cmake --build . --config Release --target ALL_BUILD
