#define BEASTHTTP_VERSION_MAJOR 2
#define BEASTHTTP_VERSION_MINOR 1

#define BEASTHTTP_VERSION_VALUE ((BEASTHTTP_VERSION_MAJOR * 10) \
                                                     + BEASTHTTP_VERSION_MINOR)
